# Generated by Django 2.1.15 on 2021-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210613_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprod',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
