# Generated by Django 2.1.15 on 2021-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20210613_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
