# Generated by Django 2.1.15 on 2021-06-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20210613_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaprod',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoriaprod',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='updated',
        ),
    ]
