# Generated by Django 2.1.15 on 2021-06-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20210613_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
