# Generated by Django 2.1.15 on 2021-06-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
