# Generated by Django 2.1.15 on 2021-06-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20210611_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel',
            field=models.CharField(max_length=9, verbose_name='Celular'),
        ),
    ]
